version: 2
jobs:
  build:
    docker:
      - image: linuxbrew/linuxbrew
    environment:
      CIRCLE_REPOSITORY_URL: https://github.com/linuxbrew/brew
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_VERBOSE: 1
      HOMEBREW_VERBOSE_USING_DOTS: 1
    steps:
      - checkout
      - run: git remote set-url origin $CIRCLE_REPOSITORY_URL
      - run: if [ -e .git/shallow ]; then echo git fetch --unshallow; fi
      - run: git config --global user.name LinuxbrewTestBot
      - run: git config --global user.email testbot@linuxbrew.sh
      - run: rm -rf /home/linuxbrew/.linuxbrew/Homebrew
      - run: cp -a . /home/linuxbrew/.linuxbrew/Homebrew
      - run: |
          umask 022
          PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
          brew test-bot
