AllCops:
  TargetRubyVersion: 2.0
  Exclude:
    - '**/.simplecov'
    - '**/Casks/**/*'
    - '**/vendor/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
    Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  CountComments: false
  Exclude:
    - 'lib/hbc/locations.rb'
    - 'lib/hbc/macos.rb'
    - 'lib/hbc/utils.rb'

Metrics/PerceivedComplexity:
  Enabled: false

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - expect
    - let
    - let!
    - subject
    - watch
    - inject
    - map
    - map!
    - collect
    - collect!
    - reject
    - reject!
    - delete_if
    - with_object
  ProceduralMethods:
    - after
    - at_exit
    - before
    - benchmark
    - bm
    - bmbm
    - capture_io
    - capture_output
    - capture_subprocess_io
    - chdir
    - context
    - create
    - define_method
    - define_singleton_method
    - each_with_object
    - fork
    - measure
    - new
    - open
    - realtime
    - shutup
    - tap
    - each
    - reverse_each
  IgnoredMethods:
    - it
    - its
    - lambda
    - proc

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/FileName:
  Regex: !ruby/regexp /^((([\dA-Z]+|[\da-z]+)(_([\dA-Z]+|[\da-z]+))*|(\-\-)?([\dA-Z]+|[\da-z]+)(-([\dA-Z]+|[\da-z]+))*))(\.rb)?$/

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/IndentArray:
  EnforcedStyle: align_brackets

Style/IndentHash:
  EnforcedStyle: align_braces

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': '{}'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '()'
    '%w': '[]'
    '%W': '[]'
    '%x': '()'

Style/PredicateName:
  NameWhitelist: is_32_bit?, is_64_bit?

Style/RaiseArgs:
  EnforcedStyle: exploded

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
